// The French CV-FRQ example for the /examples gallery: a FICTIONAL early-career
// pharmacologist's "CV descriptif" laid out exactly as the Fonds de recherche du
// Québec asks — the three FRQ sections under the FRQ's own headings, up to ten
// contributions each with its period, audience (A/B/C), role and impact, the
// owner's name in bold and an asterisk after each supervisee's name. Every person,
// institution, drug, journal, DOI and regulatory document is invented (drug names
// end in "-fictine"; DOIs use the 10.0000 test prefix). Written to answer the
// question a Québec librarian put to us: how does a narrative CV "prove" a
// contribution — by a chain the reader can follow, never by an invented number.
import type { ExampleContent } from "./examples";

export const FRQ_EXAMPLE: ExampleContent = {
  metaTitle: "Exemple de CV-FRQ (CV descriptif) — pharmacologie clinique",
  metaDescription:
    "Exemple fictif de CV descriptif du Fonds de recherche du Québec pour une pharmacologue en début de carrière : les trois sections du CV-FRQ, dix contributions avec période, clientèle A/B/C, rôle et retombées documentées, noms en gras et astérisques de supervision.",
  navLabel: "CV-FRQ (pharmacologie, français)",
  heading: "Exemple de CV-FRQ : pharmacologue clinicienne en début de carrière",
  intro: [
    "Cet exemple montre à quoi peut ressembler le CV descriptif du Fonds de recherche du Québec (CV-FRQ) pour une chercheuse en pharmacologie clinique et en pharmacovigilance qui postule à un programme de début de carrière. Il suit les instructions du FRQ à la lettre : trois sections sous les intitulés du FRQ, jusqu'à dix contributions, chacune datée, adressée à une clientèle (A. milieu académique, B. milieu de pratique, C. grand public), avec le rôle joué et les retombées ; les publications en style APA, le nom de la candidate en gras, un astérisque après le nom de chaque personne supervisée.",
    "Regardez surtout comment les retombées sont écrites. Aucun indicateur n'est inventé : chaque contribution décrit une chaîne que la personne évaluatrice peut suivre — le produit (avec son DOI ou son numéro d'enregistrement), ce qu'il a changé, et le document où ce changement est consigné (une monographie de produit, un avis de l'organisme de réglementation, un rapport ministériel, une ligne directrice). Là où l'effet ne peut pas être documenté, la contribution dit son importance et le rôle joué, et s'arrête là. C'est la façon de « prouver » qu'attend un CV narratif, en pharmacologie comme ailleurs.",
    "Dans SigmaCV, ce document s'obtient en appliquant la mise en page « CV-FRQ — CV descriptif (français) » au CV bâti depuis le dossier ORCID et OpenAlex : seules les trois sections du FRQ restent visibles, et chaque affirmation peut pointer vers une entrée réelle du dossier par un lien de preuve. Le texte se colle ensuite dans le modèle Word du FRQ et se joint en PDF dans FRQnet. Six pages au maximum en français.",
  ],
  person: {
    name: "Léa Bouchard-Nadeau",
    credentials: "B. Pharm., M. Sc., Ph. D.",
    headline:
      "Professeure adjointe en pharmacologie clinique — pharmacovigilance, détection de signaux et sécurité des médicaments en oncologie",
    affiliation: "Faculté de pharmacie, Université du Saint-Laurent (fictive)",
    location: "Québec (Québec), Canada",
  },
  citationStyle: "APA",
  templateLabel: "Classic",
  byline:
    "Pharmacologie clinique · Professeure adjointe (début de carrière) · citations APA · mise en page CV-FRQ",
  sections: [
    {
      title: "Première section : Parcours et compétences de la personne candidate",
      items: [
        "Parcours. Pharmacienne d'hôpital de formation (B. Pharm., Université du Saint-Laurent, 2013 ; résidence en pharmacie hospitalière, Centre hospitalier de la Rive fictive, 2014), j'ai fait une maîtrise en pharmacologie (2016) puis un doctorat en pharmacoépidémiologie (2020) sur la détection de signaux d'innocuité dans les bases de pharmacovigilance, suivis d'un stage postdoctoral à l'Unité de pharmacovigilance du Centre de recherche Laurentia (fictif, 2020-2021). Professeure adjointe depuis 2021, je dirige le laboratoire Signal-Onco, qui étudie la sécurité des thérapies ciblées en oncologie après leur mise en marché.",
        "Expertise pertinente pour le programme. Méthodes de détection de signaux (analyses de disproportionnalité, séries de cas, études cas-témoins nichées), pharmacoépidémiologie sur données administratives québécoises, essais cliniques selon les BPC de l'ICH (co-investigatrice sur deux essais de phase II), et cadre réglementaire des médicaments au Canada et aux États-Unis — j'ai rédigé deux notifications de signal évaluées par Santé Canada et suivi de près la procédure d'étiquetage de la FDA pendant mon postdoctorat. Cette combinaison clinique, méthodologique et réglementaire est ce que la programmation proposée exige : suivre un signal du système déclaratif jusqu'à la décision réglementaire, puis mesurer l'effet de cette décision sur la pratique.",
        "Leadership et collaborations. Co-responsable depuis 2022 du volet « sécurité des traitements » du Réseau québécois de recherche en oncologie de précision (fictif), qui réunit sept centres ; membre du comité scientifique du Centre régional de pharmacovigilance de la Capitale (fictif) ; partenariats de recherche continus avec la Direction de la pharmacovigilance du ministère fictif de la Santé et avec l'Association des pharmaciens en oncologie du Québec (fictive), pour qui je conçois des formations. Ces liens sont la raison pour laquelle mes travaux passent du signal à la pratique en quelques mois plutôt qu'en années.",
        "Effets concrets de mes travaux antérieurs. Trois de mes signaux ont mené à une modification de monographie de produit au Canada (2022, 2023, 2024) ; l'un d'eux a été repris dans une communication de sécurité de la FDA (2023). L'outil de triage des déclarations que j'ai développé pendant mon doctorat est utilisé au Centre régional de pharmacovigilance de la Capitale depuis 2021. Ces retombées sont détaillées, avec leurs références, dans la deuxième section.",
        "Reconnaissances. Prix de la relève en pharmacologie de la Société fictive de pharmacologie du Québec (2022) ; bourse de carrière de chercheuse-boursière junior 1 (fictive, 2022-2026) ; prix de la meilleure communication orale au Congrès canadien fictif de pharmacovigilance (2019).",
        "Aptitudes et compétences acquises. Bilingue français-anglais (rédaction scientifique dans les deux langues) ; programmation en R et SAS, gestion de bases de données de pharmacovigilance (format E2B) ; expérience de communication auprès du grand public acquise lors de deux années de chronique santé à la radio communautaire (voir contribution 8).",
      ],
    },
    {
      title: "Deuxième section : Contributions et expériences les plus importantes",
      items: [
        "1. Signal d'atteinte hépatique sous vorafictine et modification de la monographie canadienne (2021-2023 · clientèles A et B). Rôle : chercheuse principale, conception de l'analyse et rédaction de la notification de signal. Retombées : l'analyse de disproportionnalité sur la base canadienne des déclarations, confirmée par une série de 14 cas, a documenté un risque d'hépatotoxicité sévère non mentionné dans la monographie. La notification transmise en juin 2022 a mené à l'ajout d'une mise en garde et d'un suivi hépatique mensuel dans la monographie révisée de septembre 2023 ; la FDA a publié une communication de sécurité de portée comparable en novembre 2023. La chaîne est vérifiable : l'article, la monographie datée, l'avis public de l'organisme. Référence : Bouchard-Nadeau, L., Kaur, P.*, Moreau, D., & Tremblay, S. (2022). Hepatotoxicity signal associated with vorafictine in post-marketing reports: A disproportionality analysis and case series. Revue fictive de pharmacovigilance, 18(4), 233-245. https://doi.org/10.0000/rfpv.2022.0418",
        "2. Outil SIGNALTRI de triage des déclarations spontanées (2018-2021, en usage depuis · clientèle B). Rôle : conception et développement (doctorat), puis transfert au centre régional. Retombées : l'outil classe les déclarations d'effets indésirables par priorité d'évaluation ; validé sur 3 200 déclarations, il a réduit de 40 % le délai médian entre la réception d'une déclaration et son évaluation au Centre régional de pharmacovigilance de la Capitale (fictif), mesure faite par le centre sur les années 2021-2023 et rapportée dans son bilan annuel 2023. Code ouvert (licence MIT). Références : Bouchard-Nadeau, L., & Moreau, D. (2021). SIGNALTRI: A validated triage score for spontaneous adverse-event reports. Journal fictif d'informatique en santé, 9(2), 77-90. https://doi.org/10.0000/jfis.2021.0902 ; Bouchard-Nadeau, L. (2021). SIGNALTRI (version 1.4) [Logiciel]. Zenodo. https://doi.org/10.0000/zenodo.0000001",
        "3. Programme provincial de surveillance active des thérapies ciblées en oncologie (2022-en cours · clientèles A et B). Rôle : co-conceptrice du protocole et responsable de l'analyse. Retombées : cohorte prospective de 1 850 patients dans sept centres du réseau, qui a permis de quantifier l'incidence réelle des toxicités cardiaques de deux inhibiteurs de kinases ; le protocole a été repris par la Direction de la pharmacovigilance du ministère fictif de la Santé dans son Plan d'action 2024-2027 sur la sécurité des médicaments en oncologie (section 3.2), qui cite l'étude. Référence : Bouchard-Nadeau, L., Nguyen, T.-A.*, Fortin, É., & Tremblay, S. (2024). Real-world cardiotoxicity of kinase inhibitors in Québec: A prospective multicentre surveillance cohort. Revue fictive d'oncologie clinique, 31(1), 12-24. https://doi.org/10.0000/rfoc.2024.3101",
        "4. Avis au ministère sur la déclaration obligatoire des effets indésirables graves par les pharmaciens (2023 · clientèle B). Rôle : rédactrice principale du mémoire déposé par le Réseau québécois de recherche en oncologie de précision (fictif). Retombées : le mémoire a été cité dans le rapport de consultation du ministère fictif de la Santé (2023, p. 41-43) et deux de ses recommandations — le formulaire simplifié et le retour d'information systématique au déclarant — figurent dans la directive ministérielle entrée en vigueur en janvier 2024. Le mémoire est public. Référence : Réseau québécois de recherche en oncologie de précision. (2023). Mémoire sur la déclaration des effets indésirables graves en pharmacie (L. Bouchard-Nadeau, réd.). https://doi.org/10.0000/rqrop.2023.memoire",
        "5. Méthode d'ajustement des analyses de disproportionnalité pour le biais de notoriété (2019-2020 · clientèle A). Rôle : première auteure, conception de la méthode. Retombées : la méthode corrige l'inflation des signaux qui suit une alerte médiatique ; elle est décrite dans les lignes directrices méthodologiques fictives du Réseau canadien de pharmacovigilance (2022, annexe C) et reprise par deux équipes européennes, ce que montrent les travaux qui la citent. Importance : c'est ma contribution méthodologique la plus fondamentale et celle dont je poursuis le développement dans la présente proposition. Référence : Bouchard-Nadeau, L., & Moreau, D. (2020). Adjusting disproportionality measures for notoriety bias: A time-stratified approach. Revue fictive de pharmacoépidémiologie, 27(6), 501-513. https://doi.org/10.0000/rfpe.2020.2706",
        "6. Essai de phase II PROTECT-ONC sur la prévention des mucosites (2021-2024 · clientèles A et B). Rôle : co-investigatrice responsable de la surveillance des effets indésirables et de la pharmacovigilance de l'essai, selon les BPC de l'ICH. Retombées : essai multicentrique randomisé enregistré (fictif, NCT00000000), 212 participants ; l'analyse de sécurité que j'ai dirigée a conduit à un amendement du protocole en 2022 (ajustement de dose chez les patients de plus de 75 ans), approuvé par le comité d'éthique. Résultats publiés en 2025. Référence : Fortin, É., Bouchard-Nadeau, L., Nguyen, T.-A.*, et al. (2025). Oral cryotherapy plus fictinol for the prevention of chemotherapy-induced mucositis: The PROTECT-ONC randomized trial. Journal fictif d'oncologie, 43(2), 145-157. https://doi.org/10.0000/jfo.2025.4302",
        "7. Formation continue « Lire un signal de pharmacovigilance » pour les pharmaciens d'oncologie (2022-en cours · clientèle B). Rôle : conceptrice et formatrice principale, avec l'Association des pharmaciens en oncologie du Québec (fictive). Retombées : atelier de trois heures accrédité, donné neuf fois à 410 pharmaciens dans quatre régions ; l'évaluation post-formation montre que la proportion de participants qui déclarent un effet indésirable dans les six mois passe de 22 % à 51 % (données de l'association, 2024). C'est la contribution qui relie mes méthodes à la pratique quotidienne.",
        "8. Chronique « Le médicament en question » à la radio communautaire CKFX fictive (2019-2021 · clientèle C). Rôle : chroniqueuse. Retombées : 84 chroniques hebdomadaires de dix minutes sur la sécurité des médicaments, dont trois consacrées à la façon de déclarer un effet indésirable soi-même ; la série a été reprise en balado par la radio (fictif) et citée dans un dossier du magazine fictif Protégez-vous sur la pharmacovigilance citoyenne (mars 2021). Je ne dispose pas de mesure de son effet sur les déclarations, et je ne prétends donc pas à un tel effet.",
        "9. Jeu de données ouvert QC-ADR-ONCO (2023 · clientèles A et B). Rôle : responsable de la curation et de la documentation. Retombées : jeu de données anonymisé de 12 400 déclarations d'effets indésirables en oncologie, codées MedDRA, déposé avec un dictionnaire de données ; réutilisé par trois équipes hors du réseau à ce jour. Référence : Bouchard-Nadeau, L., Kaur, P.*, & Moreau, D. (2023). QC-ADR-ONCO: Curated oncology adverse-event reports, Québec 2015-2022 (version 2) [Jeu de données]. Dépôt fictif de données de recherche du Québec. https://doi.org/10.0000/ddrq.2023.0042",
        "10. Évaluation par les pairs et jurys (2020-en cours · clientèle A). Rôle : évaluatrice régulière pour la Revue fictive de pharmacovigilance et la Revue fictive de pharmacoépidémiologie (une vingtaine de rapports), membre d'un comité d'évaluation de bourses d'études du programme fictif de formation en oncologie (2023, 2024). Importance : une part de mon travail que je considère comme un service à la discipline, sans retombées mesurables à revendiquer.",
      ],
    },
    {
      title: "Troisième section : Activités de supervision et de mentorat",
      items: [
        "Encadrement de la relève étudiante. Depuis 2021, direction de deux étudiantes au doctorat (Priya Kaur*, pharmacoépidémiologie, dépôt prévu en 2026 ; Thi-Anh Nguyen*, pharmacologie clinique, 2022-en cours), codirection d'un étudiant à la maîtrise diplômé en 2024 (Samuel Gagnon*, maintenant pharmacien en établissement) et supervision de six stagiaires de premier cycle en pharmacie, dont trois ont présenté une affiche dans un congrès. Chaque personne supervisée est coauteure d'au moins une publication de la deuxième section ; c'est un choix délibéré : la première publication se fait pendant la formation, avec mon appui, et non après.",
        "Personnel hautement qualifié. Formation et supervision d'une coordonnatrice de recherche et d'un analyste de données (2022-en cours) ; l'analyste a suivi, à ma demande, la formation aux BPC de l'ICH et signe maintenant les rapports de sécurité de l'essai PROTECT-ONC.",
        "Enseignement et ateliers. Cours de pharmacovigilance et de pharmacoépidémiologie au programme de doctorat professionnel en pharmacie (45 heures par année depuis 2021) ; atelier annuel « Détecter un signal en trois heures » pour les résidents en pharmacie hospitalière de la province (2022, 2023, 2024) ; formation continue décrite à la contribution 7.",
        "Mentorat. Mentore de deux chercheuses en début de carrière dans le programme fictif de mentorat de la Société de pharmacologie du Québec (2023-en cours), et mentorat informel de pharmaciens cliniciens qui souhaitent publier leurs séries de cas — trois publications en ont résulté depuis 2022, dont je ne suis pas coauteure.",
        "Milieux de recherche sûrs, équitables et inclusifs. Le laboratoire Signal-Onco applique une charte de coauteurs rédigée avec les étudiants (ordre des auteurs décidé au début du projet, rôles CRediT consignés), une politique de plage horaire de réunions compatible avec les responsabilités familiales, et un recrutement de stagiaires qui réserve chaque année une place à un étudiant issu d'un programme collégial de techniques de laboratoire, en partenariat avec le Cégep fictif de la Capitale.",
      ],
    },
  ],
};
